### ISSUE TITLE
Can't log in 

### ISSUE THREAD

**Issue by Lulaschkas** [ponsato/ducopanel#1]
Hi!
First of all, really nice panel and easy installation!
But I can't log into the dashboard from my Windows PC (.exe file) it always responds incorrect password. I tried it with multiple accounts none was able to login.

**Comment by ponsato** [comment]
> Hi!
> First of all, really nice panel and easy installation!
> But I can't log into the dashboard from my Windows PC (.exe file) it always responds incorrect password. I tried it with multiple accounts none was able to login.

Hi there!  Thanks for the comment.  Actually the login is the same code as the online wallet, and the same services, so if you can enter the web wallet you should be able to enter ducopanel.  Still, I will check in the next few days to see if they have changed any of the code

**Comment by Lulaschkas** [comment]
Just tried it on Linux (PopOS) i can't login there either, just that you know.

**Comment by ponsato** [comment]
> Just tried it on Linux (PopOS) i can't login there either, just that you know.

You were absolutely right, they have changed quite a few things in the web wallet, including some access methods, so it was not possible to access from ducopanel (if it happens again, keep in mind that I have to implement everything that the Duino Coin team is doing, so sometimes it takes me a little time).

It is now fixed, and everything is updated with the latest official code, both for the wallet, miners and network.

On the other hand, in windows a false error is being generated in AVR mining, and it is because of a character ‖ that comes in the lang.json file that is generated.
If you want to fix it you have to replace the character ‖ by - in the file C:\Users\youruser\AppData\Local\Ducopanel\app-1.261.0\AVRMiner_2.61_resources\lang.json

Thanks for reporting, best regards!
